### ISSUE TITLE
Update notification card won't disappear

### ISSUE THREAD

**Issue by kz6fittycent** [pop-os/system-updater#10]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
**Issue/Bug Description:**
Update notification card will not go away until system is rebooted. Attempting to close the card fails. 

**Steps to reproduce (if you know):**
Update notification appears. Updates run, but card does not go away. Even attempting to close it with mouse fails. Only reboots remove it.

**Expected behavior:**
Should disappear when updates are finished, or when user clicks "close". 

**Other Notes:**

![Screenshot from 2022-05-03 14-52-57](https://user-images.githubusercontent.com/14829816/166556508-2a4c17b4-3a95-4512-8db9-6521250b2c43.png)

**Comment by jacobgkau** [comment]
Interesting that you have the Ubuntu logo showing instead of the Pop logo. Are you using a non-default icon theme?

When you're trying to close the notification, are you clicking the notification itself, or the X in the upper-right?

If you run `sudo apt install libnotify-bin` and then `notify-send test`, are you able to dismiss the test notification normally?

Please run the following two commands after the bad notification has shown up, then attach the resulting files from your home folder to a comment:

```
sudo journalctl -b 0 -u com.system76.SystemUpdater.service > updater-global.txt
journalctl --user -b 0 -u com.system76.SystemUpdater.Local.service > updater-global.txt
```

**Comment by kz6fittycent** [comment]
> Interesting that you have the Ubuntu logo showing instead of the Pop logo. Are you using a non-default icon theme? **_Yes, default._**
> 
> When you're trying to close the notification, are you clicking the notification itself, or the X in the upper-right? **_Both_**
> 
> If you run `sudo apt install libnotify-bin` and then `notify-send test`, are you able to dismiss the test notification normally? _**Yes, it will dismiss normally by clicking on the message.**_
> 
> Please run the following two commands after the bad notification has shown up, then attach the resulting files from your home folder to a comment:
> 
> ```
> sudo journalctl -b 0 -u com.system76.SystemUpdater.service > updater-global.txt
> journalctl --user -b 0 -u com.system76.SystemUpdater.Local.service > updater-global.txt
> ```

[updater-global.txt](https://github.com/pop-os/system-updater/files/8614159/updater-global.txt)
[updater-global-2.txt](https://github.com/pop-os/system-updater/files/8614160/updater-global-2.txt)

**Comment by jacobgkau** [comment]
This looks off:

```
May 03 09:16:16 skyfire runuser[3547]: pam_unix(runuser:session): session opened for user $USER(uid=1000) by (uid=0)
May 03 09:16:16 skyfire pop-system-updater[3558]: Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
May 03 09:16:16 skyfire runuser[3547]: pam_unix(runuser:session): session closed for user $USER
```

In my own log, `session opened for user` is always followed by a username, not `$USER` literally. And while I do have some DBUS error lines (one for each user on the system), they only show up in one spot, where yours appears to repeat farther down.

> Are you using a non-default icon theme? ***Yes, default.***

This answer doesn't make sense. Yes, you are using a non-default icon theme, or no, you are using the default?

If you create a new administrative user account under Settings -> Users and log in with that new user, does the notification dismiss properly for that one?

What other modifications have you made to the system? Have you changed your shell? If you can't think of anything else that you've changed, the output of `apt list --installed` to get a list of packages installed on your system might allow me to replicate this (if it's something caused by another package being installed.)

**Comment by kz6fittycent** [comment]
> This looks off:
> 
> ```
> May 03 09:16:16 skyfire runuser[3547]: pam_unix(runuser:session): session opened for user $USER(uid=1000) by (uid=0)
> May 03 09:16:16 skyfire pop-system-updater[3558]: Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
> May 03 09:16:16 skyfire runuser[3547]: pam_unix(runuser:session): session closed for user $USER
> ```
> 
> In my own log, `session opened for user` is always followed by a username, not `$USER` literally. And while I do have some DBUS error lines (one for each user on the system), they only show up in one spot, where yours appears to repeat farther down.
> 
**I removed my user name and added `$USER`**
> > Are you using a non-default icon theme? _**Yes, default.**_
> 
> This answer doesn't make sense. Yes, you are using a non-default icon theme, or no, you are using the default? 

**Yes, I am using the default theme.**
> 
> If you create a new administrative user account under Settings -> Users and log in with that new user, does the notification dismiss properly for that one? 
> 
> What other modifications have you made to the system? Have you changed your shell? If you can't think of anything else that you've changed, the output of `apt list --installed` to get a list of packages installed on your system might allow me to replicate this (if it's something caused by another package being installed.) 

**I've installed `snapd` but that was not problem for the system when running 21.10. After upgrading to 22.04, this issue appeared.**

**Comment by kz6fittycent** [comment]
[apt_list.txt](https://github.com/pop-os/system-updater/files/8614280/apt_list.txt)

**Comment by kz6fittycent** [comment]
Latest update came in. Closing card works as expected. Feel free to close this issue.
