### ISSUE TITLE
System Upgrades can't be disabled - again

### ISSUE THREAD

**Issue by oontra** [pop-os/system-updater#38]
Pop!_OS 22.04 LTS.

The problem from Issue #14 appears to have come back.

```
pop-system-updater:
     Installed: 0.1.0~1678118957~22.04~2e50214
     Candidate: 0.1.0~1678118957~22.04~2e50214
```
```
cat /etc/pop-system-updater/config.ron
(auto_update:false,schedule:Some((interval:128,hour:22,minute:0)))
```
The option in Settings\OS Upgrade & Recovery: Automatic updates is set to ```Off```.

When I connected to the web recently, within minutes Pop!_Shop in the dock was showing a notification badge and a notification bubble appeared showing new updates were available.

Checking ```syslog```, there is an entry dated the day of the web connection:
```
INFO pop_system_updater::service::session: next update in 592218 seconds
```
With the same date is a log entry of how many new debian packages need updating.

I'm not expecting you to rush out a patch but could you confirm sooner than later if disabling```com.system76.SystemUpdater.service unit in systemd``` like @cschmidat suggests is good enough to stop this from happening again?

**Comment by mmstick** [comment]
This is expected. It is checking for updates to give update notifications. It does not install them unless you enabled that in settings.

**Comment by oontra** [comment]
Can this automatic update checking be disabled?

I'm confused also about the purpose of the settings in OS Upgrade & Recovery:
```
Automatic Updates ON/OFF
Automatically Install OFF
```
If Automatic Updates doesn't toggle automatic update checking, and it doesn't toggle automatic update installation, then what does it do? The only thing that comes to mind is that it toggles update downloading. Am I right?

Where is the toggle for automatic update checking?

**Comment by jacobgkau** [comment]
> If Automatic Updates doesn't toggle automatic update checking, and it doesn't toggle automatic update installation...

That's what it does, it toggles automatic update installation. (Note that `Automatically Install` is both greyed out and always set to `Off` if `Automatic Updates` is switched off, because the former row is actually for the installation schedule when the switch is on.)

**Comment by jacobgkau** [comment]
To answer your earlier question, disabling `com.system76.SystemUpdater.service` should stop the automatic checks at the `Show Update Notifications` interval, if the maximum interval of one month is still too often for your taste. However, be aware that `pop-upgrade.service` will also check for updates (and update itself, but no other packages) on boot and when you open the Settings app to the `OS Upgrade & Recovery` page. This is because `pop-upgrade` performs sensitive package manager operations when it's used, and it may break the system if it's out-of-date and missing an important fix; you may need to disable or mask that one as well if you don't want that either (but doing so will prevent that page of Settings from displaying properly until you undo that.)

**Comment by jacobgkau** [comment]
I'm going to go ahead and close the issue since what you're describing wasn't actually upgrades being installed, but please let us know if you have any other questions. Do remember you can unpin the Pop!_Shop from the dock as well if you find the available updates badge to be a bother.
